Enhance missing command detection
If a given command/tools is not executable or blocked from execution by a LSM
(SELinux/AppArmor) for example, then consider that VCS to be unavailable.

This change prevents the following error when running 'bumpversion --help'

    OSError: [Error 13] Permission denied